site_name: ChainPact Docs
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
    # primary: black
    # accent: deep purple
    # scheme: slate

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"    
      scheme: default
      primary: white
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"      
      scheme: slate
      primary: blue-grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  # features:
  